# Generated by Django 5.0.4 on 2024-04-14 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="link name")),
                (
                    "href",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="link suffix"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="childrens",
                        to="menu.menu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Меню",
                "verbose_name_plural": "Меню",
            },
        ),
    ]
