# Generated by Django 5.0.4 on 2024-04-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="href",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="link suffix"
            ),
        ),
    ]
