# Generated by Django 5.0.4 on 2024-04-14 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="name",
            field=models.CharField(
                help_text="Название ссылки. Не короче 3 знаков.",
                max_length=30,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="link name",
            ),
        ),
    ]
